  - name = generate the server locale
    locale_gen: name = {{ locale }} state = present

  - name: set locale
    lineinfile: dest=/etc/default/locale ragexp='^LANG' line='LANG={{ locale }}'

  - name: reload locale
    raw: . /etc/default/locale
    
