Vagrant.configure("2") do |config|

  config.vm.define "test" do |test|

    config.vm.box = "ubuntu/trusty64"

    config.vm.hostname = "test.dev"

    config.vm.network :private_network, ip: "192.168.56.1"

  #
  # Run Ansible from the Vagrant Host
  #
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"

    end
  end

  config.vm.define "sonar01" do |h|
    h.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", "4096"]
    end

      h.vm.host_name = "sonar01"
      h.vm.network "private_network", ip: "192.168.135.101"
      h.vm.network "forwarded_port", guest: "9000", host: "9000", host_ip: "127.0.0.1"
      h.vm.network "forwarded_port", guest: "5432", host: "5432", host_ip: "127.0.0.1"
      h.vm.network "forwarded_port", guest: "80", host: "80", host_ip: "127.0.0.1"
      h.vm.network "forwarded_port", guest: "443", host: "443", host_ip: "127.0.0.1"
      h.vm.provision :shell, path: "vagrant/generic.ubuntu.sh"
    end

  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
  end
end
